# Generated by Django 5.2.14 on 2026-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Адресс')),
            ],
        ),
    ]
