# Generated by Django 5.2.14 on 2026-05-19 16:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=128, region='RU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
