# Generated by Django 5.2.14 on 2026-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
